### ISSUE TITLE
Adding extra fields on User model

### ISSUE THREAD

**Issue by pragmaticivan** [mustafaturan/shield#32]
Which approach would you recommend here to add new fields. I'm trying to implement a simple multitenancy approach and maybe add a field `name`.

Would you overwrite the module `Shield.Policy.User.Register` or something else in order to change the behavior of the changeset for that.

**Comment by gmile** [comment]
@pragmaticivan I would go with a adding a `profiles` table, with `user_id` foreign key pointing to `authable` users.

One problem is that `conn.current_user` would still represent `authable` user, and not your shiny `profile`. To aid that, you'd want to have user's `profile` loaded in a plug of your own, right after the authentication such as [this one](https://github.com/mustafaturan/shield-blog-sample/blob/master/web/controllers/post_controller.ex#L6), for example.

Another option would be to store all custom data in `users.settings` field. Since it's [not used](https://github.com/mustafaturan/authable/search?utf8=%E2%9C%93&q=settings&type=) anywhere in the shield, I assume it was reserved specifically to store arbitrary data alongside users.

**Comment by mustafaturan** [comment]
I agree with @gmile, I would prefer to create a new table. 

But if you deadly need to add a field to current table: 
Firstly, you have to modify the migration file and then rename the generated `Authable.Model.User` to another module name then change the `Authable.Model.User` to the new name on `config` file.

---

@gmile 
Shield is using `settings` field to store some special public info like `email_confirmed`, `otp_enabled(one time password)`.  For reference, you can check `Shield.SettingController`.
