### ISSUE TITLE
How to use client credentials?

### ISSUE THREAD

**Issue by kevinblade** [mustafaturan/shield#8]
Hi!
Thank you your great job for this. Do you have plan to upgrade this project as like doorkeeper for Rails?
Let me know how to use to protect my API service with client credentials with shield.
Thank you for your great job.

**Comment by mustafaturan** [comment]
I will make a few more enhancement. And I will share two posts about how to use shield as an OAuth2 provider and as a separate microservice soon. For now checkout ui branch of work. Follow me on medium.com/@mustafaturan.

Cheers,

**Comment by angelomachado** [comment]
> Could you upload a non-minified version of the Ember application?

It would be awesome

**Comment by edevil** [comment]
@mustafaturan Hello. Are you still thinking of producing those blog posts about building an OAuth2 provider using Shield? It would be great.

**Comment by mustafaturan** [comment]
Hi all,
I will try to create a wiki page this weekend. But I strongly recommend you guys check swagger documentation. 

> You can use paste the content of swagger.yml to http://editor.swagger.io/ https://raw.githubusercontent.com/mustafaturan/shield/master/swagger.yml

**Comment by edevil** [comment]
@mustafaturan Thank you. Maybe you can already enlighten me on a question that I have. I need to build a web application that will require user management (register/login/logout) and will also require an OAuth2 provider implementation for a simple API that it will serve. It seems to me that Shield, besides providing the usual OAuth endpoints, also provides authentication endpoints for user management:
```
  user_path  POST    /users/register          Shield.UserController :register
  user_path  POST    /users/login             Shield.UserController :login
  user_path  DELETE  /users/logout            Shield.UserController :logout
  user_path  GET     /users/me                Shield.UserController :me
  user_path  GET     /users/confirm           Shield.UserController :confirm
  user_path  POST    /users/recover_password  Shield.UserController :recover_password
  user_path  POST    /users/reset_password    Shield.UserController :reset_password
  user_path  POST    /users/change_password   Shield.UserController :change_password
```

Am I right? However, I would like to integrate this functionality directly in my app not not have to make API requests to shield. Can Shield help me here? Or the lower-level "Authable" module?

Thanks for the help.

**Comment by mustafaturan** [comment]
@edevil If you need those endpoints on your app just use the instructions on `README.md` , in case you need a UI for those endpoints you need to run step number 7 (`mix shield.install`) and create your own view files for the controllers.

**Comment by edevil** [comment]
@mustafaturan I've already done that, I just want to make clear the work I have ahead of me. In order to use the existing actions (login, logout) directly with browsers, they all have to be changed in order not to return JSON but HTML, right? For example, when there is an error in the register form a response is returned with the :unprocessable_entity http status and the content is a generic render of a changeset error. Just through configuration it doesn't seem possible to have a register specific html template show the form with the changeset errors like we would on a normal web app.

**Comment by mustafaturan** [comment]
@edevil 
Sorry, since its aim is to provide rest endpoints and helper methods, you can not do it directly by configuration.  There is no plan to add html support for it even in version 1. But you can still use `mix shield.install` to generate controllers and rewrite with little change for the html support.

**Comment by mustafaturan** [comment]
https://github.com/mustafaturan/shield/wiki/5-min-walk-to-Becoming-OAuth2-Provider-and-Protecting-Resources-using-Shield-and-Phoenix-Framework
